#!/bin/sh
mkdir -p /tmp/tailscale
/var/runtime/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
if [ -n "${TAILSCALE_AUTHKEY}" ]; then
  until /var/runtime/tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname=aws-lambda-app
  do
      sleep 0.1
  done
  echo Tailscale started
  export ALL_PROXY="socks5://localhost:1055/"
fi

if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
  exec /usr/local/bin/aws-lambda-rie /var/lang/bin/python3 -m awslambdaric $@
else
  exec /var/lang/bin/python3 -m awslambdaric $@
fi
